/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Build-time version stamp.  Generated by scripts/sync-version.sh; the
 * single source of truth is the GitHub repository variable VERSION.
 * Do not edit by hand.
 */
#ifndef LGMAGIC_BUILD_VERSION_H
#define LGMAGIC_BUILD_VERSION_H

#define LGMAGIC_VERSION "0.0.1"

#endif /* LGMAGIC_BUILD_VERSION_H */
