/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * test_dbus_client.c - unit tests for the zero-dependency D-Bus client
 * (dbus_client.h).
 *
 * Covers:
 *   - the AUTH EXTERNAL handshake byte-for-byte (uid as a decimal string,
 *     hex-encoded as the initial-response argument per the D-Bus spec,
 *     leading NUL, CRLF; OK/BEGIN; REJECTED)
 *   - golden-bytes marshaling of METHOD_CALLs (headers incl. 8-aligned
 *     field values, body for s/d/u, empty signature) verified against
 *     independently generated constants (see the comment below)
 *   - unmarshaling of METHOD_RETURN with s / as / v(s) / empty body
 *   - D-Bus ERROR replies (name + message)
 *   - reply-serial matching, bad endian marker, unexpected message type,
 *     oversized reply, chunked delivery
 *   - connection error paths and argument validation
 *
 * The fake bus runs in a pthread (available in libc on glibc >= 2.34 and
 * on macOS).  Every read on the fake bus side is bounded by poll so a
 * broken client fails the test in ~3 s instead of hanging it.
 *
 * The golden byte strings were generated by an independent Python
 * implementation of the D-Bus wire rules (tools-independent cross-check)
 * and are additionally validated against a real dbus-daemon in CI.
 */
#include <poll.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdio.h>
#include <sys/socket.h>
#include <sys/un.h>

#include "test_util.h"
#include "dbus_client.h"

#define MAX_TEST_MSG 4096

/* ------------------------------------------------------------------ */
/* Golden byte strings (plain hex, decoded by hex_decode).             */
/* ------------------------------------------------------------------ */

/* request: org.freedesktop.DBus.Hello, sig '', serial 1 (128 bytes) - the
 * first message of every connection (a real dbus-daemon closes connections
 * whose first message is not Hello).  fields_len 0x6d excludes the trailing
 * padding of the last field, 128 bytes on the wire. */
static const char GOLDEN_CALL_HELLO[] =
	"6c01000100000000010000006d000000"
	"01016f00150000002f6f72672f667265"
	"656465736b746f702f44427573000000"
	"02017300140000006f72672e66726565"
	"6465736b746f702e4442757300000000"
	"030173000500000048656c6c6f000000"
	"06017300140000006f72672e66726565"
	"6465736b746f702e4442757300000000";

/* request: SetScrollSpeed, sig 'sd', args (s "aa:bb", d 2.0), serial 2 (160 bytes) */
static const char GOLDEN_CALL_SD[] =
	"6c010001180000000200000078000000"
	"01016f00140000002f6f72672f6c676d"
	"616769632f4d616e6167657200000000"
	"02017300130000006f72672e6c676d61"
	"6769632e4d616e616765720000000000"
	"030173000e0000005365745363726f6c"
	"6c53706565640000060173000b000000"
	"6f72672e6c676d616769630000000000"
	"08016700027364000500000061613a62"
	"62000000000000000000000000000040";

/* request: GetStatus, sig 's', arg "AA:BB:CC:DD:EE:FF", serial 2 (158 bytes) */
static const char GOLDEN_CALL_S[] =
	"6c010001160000000200000077000000"
	"01016f00140000002f6f72672f6c676d"
	"616769632f4d616e6167657200000000"
	"02017300130000006f72672e6c676d61"
	"6769632e4d616e616765720000000000"
	"03017300090000004765745374617475"
	"7300000000000000060173000b000000"
	"6f72672e6c676d616769630000000000"
	"08016700017300001100000041413a42"
	"423a43433a44443a45453a464600";

/* request: Reload, sig '', serial 2 (120 bytes) */
static const char GOLDEN_CALL_EMPTY[] =
	"6c010001000000000200000064000000"
	"01016f00140000002f6f72672f6c676d"
	"616769632f4d616e6167657200000000"
	"02017300130000006f72672e6c676d61"
	"6769632e4d616e616765720000000000"
	"030173000600000052656c6f61640000"
	"060173000b0000006f72672e6c676d61"
	"6769630000000000";

/* request: GetStatus ..., serial 3 (158 bytes) */
static const char GOLDEN_CALL_S2[] =
	"6c010001160000000300000077000000"
	"01016f00140000002f6f72672f6c676d"
	"616769632f4d616e6167657200000000"
	"02017300130000006f72672e6c676d61"
	"6769632e4d616e616765720000000000"
	"03017300090000004765745374617475"
	"7300000000000000060173000b000000"
	"6f72672e6c676d616769630000000000"
	"08016700017300001100000041413a42"
	"423a43433a44443a45453a464600";

/* reply: METHOD_RETURN s "status-line", serial 2 (48 bytes) */
static const char GOLDEN_REPLY_S[] =
	"6c02000110000000020000000f000000"
	"05017500020000000801670001730000"
	"0b0000007374617475732d6c696e6500";

/* reply: METHOD_RETURN as [AA_BB, CC_DD], serial 2 (58 bytes) */
static const char GOLDEN_REPLY_AS[] =
	"6c0200011a0000000200000010000000"
	"05017500020000000801670002617300"
	"160000000500000041415f4242000000"
	"0500000043435f444400";

/* reply: METHOD_RETURN v(s) "hello", serial 2 (46 bytes) */
static const char GOLDEN_REPLY_VS[] =
	"6c0200010e000000010000000f000000"
	"05017500020000000801670001760000"
	"017300000500000068656c6c6f00";

/* reply: ERROR org.lgmagic.Error.NotAuthorized "permission denied" (86 bytes) */
static const char GOLDEN_REPLY_ERROR[] =
	"6c030001160000000200000030000000"
	"040173001f0000006f72672e6c676d61"
	"6769632e4572726f722e4e6f74417574"
	"686f72697a6564000501750002000000"
	"110000007065726d697373696f6e2064"
	"656e69656400";

/* reply: METHOD_RETURN s "status-line", serial 3 (48 bytes) */
static const char GOLDEN_REPLY_S2[] =
	"6c02000110000000030000000f000000"
	"05017500030000000801670001730000"
	"0b0000007374617475732d6c696e6500";

/* reply: METHOD_RETURN s "status-line", WRONG serial 7 (48 bytes) */
static const char GOLDEN_REPLY_WRONG_SERIAL[] =
	"6c02000110000000070000000f000000"
	"05017500070000000801670001730000"
	"0b0000007374617475732d6c696e6500";

/* reply: METHOD_RETURN empty (no SIGNATURE field), serial 2 (24 bytes) */
static const char GOLDEN_REPLY_EMPTY[] =
	"6c020001000000000200000008000000"
	"0501750002000000";

/* reply: garbage type 127 (16 bytes) */
static const char GOLDEN_REPLY_BAD_TYPE[] =
	"6c7f0001000000000100000000000000";

/* reply: real dbus-daemon reply to Hello (DEST+REPLY_SERIAL+SIGNATURE+
 * SENDER+UNIX_FDS), serial 1 (89 bytes) - the fake bus must send this after
 * the client's Hello or the client never proceeds */
static const char GOLDEN_REPLY_HELLO[] =
	"6c02010109000000010000003d000000"
	"06017300040000003a312e3000000000"
	"0501750001000000"
	"0801670001730000"
	"07017300140000006f72672e66726565"
	"6465736b746f702e4442757300000000"
	"040000003a312e3000";

/* reply: real dbus-daemon Hello reply (DEST+REPLY_SERIAL+SIGNATURE+SENDER), serial 3 (89 bytes) */
static const char GOLDEN_REPLY_DAEMON[] =
	"6c02010109000000030000003d000000"
	"06017300040000003a312e3000000000"
	"05017500030000000801670001730000"
	"07017300140000006f72672e66726565"
	"6465736b746f702e4442757300000000"
	"040000003a312e3000";

/* signal: real dbus-daemon NameAcquired, serial 2 (169 bytes) */
static const char GOLDEN_SIGNAL_NAMEACQUIRED[] =
	"6c04010109000000020000008d000000"
	"01016f00150000002f6f72672f667265"
	"656465736b746f702f44427573000000"
	"02017300140000006f72672e66726565"
	"6465736b746f702e4442757300000000"
	"030173000c0000004e616d6541637175"
	"69726564000000000601730004000000"
	"3a312e30000000000801670001730000"
	"07017300140000006f72672e66726565"
	"6465736b746f702e4442757300000000"
	"040000003a312e3000";

/* reply: bad endian marker (16 bytes) */
static const char GOLDEN_REPLY_BAD_ENDIAN[] =
	"42020001000000000100000000000000";

/* reply: body_len above the sanity cap (16 bytes) */
static const char GOLDEN_REPLY_OVERSIZED[] =
	"6c020001000020000100000000000000";

/* ------------------------------------------------------------------ */
/* Fake bus server                                                      */
/* ------------------------------------------------------------------ */

struct scenario {
	const char *name;
	const char *sock_path;
	int auth_reject;		/* reply REJECTED instead of OK */
	int expect_ncalls;		/* METHOD_CALLs to serve */
	const char *expect_hex[4];	/* per-call expected raw bytes */
	const char *reply_hex[4];	/* per-call canned reply */
	const char *preamble_hex;	/* sent before the first reply (e.g. a
					 * SIGNAL the client must skip) */
	int reply_chunks;		/* send replies in this many chunks */
	int rc;				/* server verdict (0 = as expected) */
	char failmsg[256];
	pthread_mutex_t m;		/* readiness signaling */
	pthread_cond_t cv;
	int ready;
};

static int hexval(int c)
{
	if (c >= '0' && c <= '9')
		return c - '0';
	if (c >= 'a' && c <= 'f')
		return c - 'a' + 10;
	if (c >= 'A' && c <= 'F')
		return c - 'A' + 10;
	return -1;
}

static size_t hex_decode(const char *s, unsigned char *out, size_t outsz)
{
	size_t n = 0;

	while (s[0] && s[1]) {
		int hi = hexval((unsigned char)s[0]);
		int lo = hexval((unsigned char)s[1]);

		if (hi < 0 || lo < 0 || n >= outsz)
			return 0;
		out[n++] = (unsigned char)((hi << 4) | lo);
		s += 2;
	}
	return n;
}

static void srv_fail(struct scenario *s, const char *fmt, ...)
{
	va_list ap;

	if (s->rc == -1)
		return;			/* keep the first failure */
	s->rc = -1;
	va_start(ap, fmt);
	vsnprintf(s->failmsg, sizeof s->failmsg, fmt, ap);
	va_end(ap);
}

static int srv_wait(int fd)
{
	struct pollfd pfd = { fd, POLLIN, 0 };

	for (;;) {
		int rc = poll(&pfd, 1, 3000);

		if (rc < 0 && errno == EINTR)
			continue;
		return rc > 0 ? 0 : -1;
	}
}

static int srv_read_exact(int fd, unsigned char *buf, size_t n)
{
	size_t got = 0;

	while (got < n) {
		ssize_t r;

		if (srv_wait(fd) < 0)
			return -1;
		r = recv(fd, buf + got, n - got, 0);
		if (r <= 0)
			return -1;
		got += (size_t)r;
	}
	return 0;
}

/* read raw bytes up to and including '\n'; returns the count */
static int srv_read_line(int fd, unsigned char *buf, size_t bufsz)
{
	size_t n = 0;

	while (n < bufsz) {
		ssize_t r;

		if (srv_wait(fd) < 0)
			return -1;
		r = recv(fd, buf + n, 1, 0);
		if (r <= 0)
			return -1;
		n++;
		if (buf[n - 1] == '\n')
			return (int)n;
	}
	return -1;
}

static int srv_write_all(int fd, const void *buf, size_t n)
{
	const unsigned char *p = buf;

	while (n) {
		ssize_t w = send(fd, p, n, 0);

		if (w <= 0)
			return -1;
		p += w;
		n -= (size_t)w;
	}
	return 0;
}

/* read one full D-Bus message (fixed header + fields + padded + body) */
static int srv_read_msg(int fd, unsigned char *buf, size_t *len_out)
{
	uint32_t body_len, fields_len;
	size_t hdr_pad, total;

	if (srv_read_exact(fd, buf, 16) < 0)
		return -1;
	body_len = (uint32_t)buf[4] | (uint32_t)buf[5] << 8 |
		   (uint32_t)buf[6] << 16 | (uint32_t)buf[7] << 24;
	fields_len = (uint32_t)buf[12] | (uint32_t)buf[13] << 8 |
		     (uint32_t)buf[14] << 16 | (uint32_t)buf[15] << 24;
	if (body_len > MAX_TEST_MSG || fields_len > MAX_TEST_MSG)
		return -1;
	hdr_pad = (8 - ((16 + fields_len) % 8)) % 8;
	total = 16 + fields_len + hdr_pad + body_len;
	if (total > MAX_TEST_MSG)
		return -1;
	if (srv_read_exact(fd, buf + 16, total - 16) < 0)
		return -1;
	*len_out = total;
	return 0;
}

static void *server_main(void *arg)
{
	struct scenario *s = arg;
	int lfd = -1, cfd = -1;
	struct sockaddr_un a;
	unsigned char raw[MAX_TEST_MSG];
	unsigned char want[MAX_TEST_MSG];
	size_t n;
	int i;

	lfd = socket(AF_UNIX, SOCK_STREAM, 0);
	if (lfd < 0) {
		srv_fail(s, "cannot create the fake bus socket");
		goto done;
	}
	memset(&a, 0, sizeof a);
	a.sun_family = AF_UNIX;
	strncpy(a.sun_path, s->sock_path, sizeof a.sun_path - 1);
	unlink(s->sock_path);
	if (bind(lfd, (struct sockaddr *)&a, sizeof a) < 0 ||
	    listen(lfd, 1) < 0) {
		srv_fail(s, "cannot bind the fake bus socket: %s",
			 strerror(errno));
		goto done;
	}

	/* signal readiness so the client's connect() cannot race listen() */
	pthread_mutex_lock(&s->m);
	s->ready = 1;
	pthread_cond_broadcast(&s->cv);
	pthread_mutex_unlock(&s->m);

	if (srv_wait(lfd) < 0) {
		srv_fail(s, "the client never connected");
		goto done;
	}
	cfd = accept(lfd, NULL, NULL);
	if (cfd < 0) {
		srv_fail(s, "accept failed");
		goto done;
	}

	/* AUTH handshake: "\0AUTH EXTERNAL <hex-of-uid-decimal>\r\n" - the
	 * uid as a decimal string, HEX-ENCODED as the initial response (the
	 * D-Bus spec encodes the argument; the reference daemon decodes the
	 * hex and then parses the uid base 10).  Computed independently
	 * here, mirroring the client. */
	if (srv_read_line(cfd, raw, sizeof raw) < 0) {
		srv_fail(s, "no AUTH line from the client");
		goto done;
	}
	{
		static const char hex[] = "0123456789abcdef";
		unsigned char expect[64];
		char dec[24];
		int dlen = snprintf(dec, sizeof dec, "%lu",
				    (unsigned long)getuid());
		int elen = snprintf((char *)expect + 1, sizeof expect - 1,
				    "AUTH EXTERNAL ");
		int i;

		if (dlen < 0 ||
		    1 + elen + 2 * dlen + 2 > (int)sizeof expect)
			srv_fail(s, "uid too long to build the expectation");
		else {
			for (i = 0; i < dlen; i++) {
				expect[1 + elen + 2 * i] =
					(unsigned char)hex[(dec[i] >> 4) & 0xf];
				expect[1 + elen + 2 * i + 1] =
					(unsigned char)hex[dec[i] & 0xf];
			}
			elen += 2 * dlen;
			expect[1 + elen] = '\r';
			expect[1 + elen + 1] = '\n';
			expect[0] = '\0';
			if (raw[0] != '\0' ||
			    memcmp(raw, expect, (size_t)1 + elen + 2) != 0)
				srv_fail(s, "AUTH line mismatch "
					 "(want \\0AUTH EXTERNAL "
					 "<hex-of-uid-decimal>\\r\\n)");
		}
	}
	if (s->auth_reject) {
		srv_write_all(cfd, "REJECTED EXTERNAL\r\n", 19);
		goto done;
	}
	srv_write_all(cfd, "OK 0123456789abcdef0123456789abcdef\r\n", 37);

	if (srv_read_line(cfd, raw, sizeof raw) < 0) {
		srv_fail(s, "no BEGIN line from the client");
		goto done;
	}
	if (memcmp(raw, "BEGIN", 5) != 0)
		srv_fail(s, "expected the BEGIN command");
	/* The real dbus-daemon sends no reply to BEGIN - it switches to
	 * binary mode silently and the first bytes it produces are the first
	 * message reply (verified against dbus 1.14 via strace).  The first
	 * binary message must be Hello (the daemon closes connections whose
	 * first message is anything else), so the client sends it right after
	 * BEGIN; we verify it and reply exactly as the daemon does. */
	if (srv_read_msg(cfd, raw, &n) < 0) {
		srv_fail(s, "no Hello message from the client");
		goto done;
	}
	{
		size_t hlen = hex_decode(GOLDEN_CALL_HELLO, want, sizeof want);

		if (hlen == 0 || hlen != n || memcmp(raw, want, hlen) != 0)
			srv_fail(s, "the Hello message does not match the golden "
				 "bytes");
	}
	{
		size_t rlen = hex_decode(GOLDEN_REPLY_HELLO, want, sizeof want);

		if (rlen == 0) {
			srv_fail(s, "bad Hello reply hex");
			goto done;
		}
		srv_write_all(cfd, want, rlen);
	}
	/* the real bus may deliver a SIGNAL (e.g. NameAcquired) right after
	 * the Hello reply, before the reply to the first call - the client
	 * must read and skip it */
	if (s->preamble_hex) {
		size_t plen = hex_decode(s->preamble_hex, want, sizeof want);

		if (plen == 0) {
			srv_fail(s, "bad preamble hex");
			goto done;
		}
		srv_write_all(cfd, want, plen);
	}
	/* scenarios that expect no calls: the client must not send anything
	 * after Hello - an EOF here is the pass (srv_read_msg returns -1 on
	 * EOF, 0 on a complete message) */
	if (s->expect_ncalls == 0) {
		if (srv_read_msg(cfd, raw, &n) == 0)
			srv_fail(s, "the client sent a call when none was "
				 "expected");
		goto done;
	}

	for (i = 0; i < s->expect_ncalls; i++) {
		if (srv_read_msg(cfd, raw, &n) < 0) {
			srv_fail(s, "cannot read method call %d", i + 1);
			goto done;
		}
		if (s->expect_hex[i]) {
			size_t wlen = hex_decode(s->expect_hex[i], want,
						 sizeof want);

			if (wlen == 0 || wlen != n || memcmp(raw, want, n) != 0)
				srv_fail(s, "method call %d does not match the "
					 "golden bytes", i + 1);
		}
		if (s->reply_hex[i]) {
			size_t rlen = hex_decode(s->reply_hex[i], want,
						 sizeof want);

			if (rlen == 0) {
				srv_fail(s, "bad reply hex for call %d", i + 1);
				goto done;
			}
			if (s->reply_chunks == 2 && rlen >= 2) {
				srv_write_all(cfd, want, rlen / 2);
				usleep(30000);
				srv_write_all(cfd, want + rlen / 2,
					      rlen - rlen / 2);
			} else {
				srv_write_all(cfd, want, rlen);
			}
		}
	}
	if (s->rc != -1)
		s->rc = 0;		/* everything matched */

done:
	if (cfd >= 0)
		close(cfd);
	if (lfd >= 0)
		close(lfd);
	unlink(s->sock_path);
	return NULL;
}

static void scenario_init(struct scenario *s, const char *name)
{
	memset(s, 0, sizeof *s);
	s->name = name;
	s->reply_chunks = 1;
	pthread_mutex_init(&s->m, NULL);
	pthread_cond_init(&s->cv, NULL);
}

/* start the fake bus, wait until it is listening, return the thread */
static pthread_t start_server(struct scenario *s, char *sockpath, size_t sz)
{
	static int counter;
	const char *dir = getenv("TMPDIR");
	pthread_t th;

	if (!dir || !*dir)
		dir = "/tmp";
	snprintf(sockpath, sz, "%s/lgmagic-dbus-%d-%d.sock", dir,
		 (int)getpid(), counter++);
	s->sock_path = sockpath;
	if (pthread_create(&th, NULL, server_main, s) != 0) {
		fprintf(stderr, "cannot create the fake bus thread\n");
		exit(2);
	}
	pthread_mutex_lock(&s->m);
	while (!s->ready)
		pthread_cond_wait(&s->cv, &s->m);
	pthread_mutex_unlock(&s->m);
	return th;
}

static void finish_server(struct scenario *s, pthread_t th,
			  const char *check_name)
{
	pthread_join(th, NULL);
	if (s->rc == 0) {
		tu_pass_count++;
		printf("PASS %s\n", check_name);
	} else {
		tu_fail_count++;
		printf("FAIL %s: %s\n", check_name,
		       s->failmsg[0] ? s->failmsg : "fake bus failed");
	}
}

/* ------------------------------------------------------------------ */
/* Tests                                                               */
/* ------------------------------------------------------------------ */

static void test_golden_sd(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "golden sd");
	s.expect_ncalls = 1;
	s.expect_hex[0] = GOLDEN_CALL_SD;
	s.reply_hex[0] = GOLDEN_REPLY_EMPTY;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_arg args[2] = {
			{ 's', .s = "aa:bb" },
			{ 'd', .d = 2.0 },
		};
		struct dbus_value *out = NULL;

		CHECK_INT_EQ(dbus_connect(&c, addr, err, sizeof err), 0,
			     "connect to the fake bus");
		CHECK_INT_EQ(dbus_call(&c, "SetScrollSpeed", "sd", args, NULL,
				       NULL, &out, err, sizeof err), 0,
			     "sd call returns 0");
		CHECK(out != NULL && out->type == DBUS_VALUE_EMPTY,
		      "empty reply parses as DBUS_VALUE_EMPTY");
		dbus_value_free(out);
		dbus_disconnect(&c);
	}
	finish_server(&s, th,
		      "fake bus saw the exact SetScrollSpeed wire bytes");
}

static void test_golden_s_reply(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "golden s");
	s.expect_ncalls = 1;
	s.expect_hex[0] = GOLDEN_CALL_S;
	s.reply_hex[0] = GOLDEN_REPLY_S;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_arg args[1] = { { 's', .s = "AA:BB:CC:DD:EE:FF" } };
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "GetStatus", "s", args,
					       NULL, NULL, &out, err,
					       sizeof err), 0,
				     "s call returns 0");
			CHECK(out != NULL && out->type == DBUS_VALUE_STRING &&
			      out->str != NULL &&
			      strcmp(out->str, "status-line") == 0,
			      "reply string is \"status-line\"");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th,
		      "fake bus saw the exact GetStatus wire bytes");
}

static void test_golden_empty(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "golden empty");
	s.expect_ncalls = 1;
	s.expect_hex[0] = GOLDEN_CALL_EMPTY;
	s.reply_hex[0] = GOLDEN_REPLY_EMPTY;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, &out, err, sizeof err),
				     0, "empty-signature call returns 0");
			CHECK(out != NULL && out->type == DBUS_VALUE_EMPTY,
			      "empty-signature reply is EMPTY");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus saw the exact Reload wire bytes");
}

static void test_two_calls_serials(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "two calls");
	s.expect_ncalls = 2;
	s.expect_hex[0] = GOLDEN_CALL_S;
	s.expect_hex[1] = GOLDEN_CALL_S2;
	s.reply_hex[0] = GOLDEN_REPLY_S;
	s.reply_hex[1] = GOLDEN_REPLY_S2;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_arg args[1] = { { 's', .s = "AA:BB:CC:DD:EE:FF" } };

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			struct dbus_value *out1 = NULL, *out2 = NULL;

			CHECK_INT_EQ(dbus_call(&c, "GetStatus", "s", args,
					       NULL, NULL, &out1, err,
					       sizeof err), 0,
				     "first call returns 0");
			CHECK_INT_EQ(dbus_call(&c, "GetStatus", "s", args,
					       NULL, NULL, &out2, err,
					       sizeof err), 0,
				     "second call returns 0");
			CHECK(out1 && out1->type == DBUS_VALUE_STRING &&
			      !strcmp(out1->str, "status-line") &&
			      out2 && out2->type == DBUS_VALUE_STRING &&
			      !strcmp(out2->str, "status-line"),
			      "both replies parse");
			dbus_value_free(out1);
			dbus_value_free(out2);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus saw serials 2 then 3");
}

static void test_reply_as(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "reply as");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_AS;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "ListDevices", "", NULL,
					       NULL, NULL, &out, err,
					       sizeof err), 0,
				     "as call returns 0");
			CHECK(out != NULL && out->type ==
			      DBUS_VALUE_STRING_ARRAY && out->n == 2 &&
			      out->items && out->items[0] && out->items[1] &&
			      strcmp(out->items[0], "AA_BB") == 0 &&
			      strcmp(out->items[1], "CC_DD") == 0,
			      "as reply has [AA_BB, CC_DD]");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for an as reply");
}

static void test_reply_vs(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "reply v(s)");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_VS;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_value *out = NULL;
		struct dbus_arg args[1] = { { 's', .s = "AA:BB:CC:DD:EE:FF" } };

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Get", "s", args, NULL,
					       NULL, &out, err, sizeof err),
				     0, "v(s) call returns 0");
			CHECK(out != NULL && out->type == DBUS_VALUE_VARIANT &&
			      out->var_sig && strcmp(out->var_sig, "s") == 0 &&
			      out->var && out->var->type == DBUS_VALUE_STRING &&
			      out->var->str && strcmp(out->var->str,
						      "hello") == 0,
			      "v(s) reply carries sig 's' and \"hello\"");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for a v(s) reply");
}

static void test_reply_error(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "reply error");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_ERROR;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_value *out = NULL;
		char *err_name = NULL, *err_msg = NULL;
		struct dbus_arg args[1] = { { 's', .s = "AA:BB:CC:DD:EE:FF" } };

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "GetStatus", "s", args,
					       &err_name, &err_msg, &out, err,
					       sizeof err), 1,
				     "ERROR reply returns 1");
			CHECK(out == NULL, "ERROR reply sets no out value");
			CHECK_STR_EQ(err_name,
				     "org.lgmagic.Error.NotAuthorized",
				     "ERROR reply carries the error name");
			CHECK_STR_EQ(err_msg, "permission denied",
				     "ERROR reply carries the message");
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for an ERROR reply");
}

static void test_wrong_serial(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "wrong serial");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_WRONG_SERIAL;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, &out, err, sizeof err),
				     -1, "reply with a wrong serial fails");
			CHECK(strstr(err, "serial") != NULL,
			      "the error mentions the serial");
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for a serial mismatch");
}

/* the real bus delivers a NameAcquired SIGNAL right after the Hello
 * reply; the client must read and skip it, then keep waiting */
static void test_signal_skip(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "signal skip");
	s.expect_ncalls = 1;
	s.expect_hex[0] = GOLDEN_CALL_S;
	s.preamble_hex = GOLDEN_SIGNAL_NAMEACQUIRED;
	s.reply_hex[0] = GOLDEN_REPLY_S;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_arg args[1] = { { 's', .s = "AA:BB:CC:DD:EE:FF" } };
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "GetStatus", "s", args, NULL,
					       NULL, &out, err, sizeof err), 0,
				     "the call succeeds despite a leading signal");
			CHECK(out != NULL && out->type == DBUS_VALUE_STRING &&
			      out->str != NULL &&
			      strcmp(out->str, "status-line") == 0,
			      "the reply after the signal is the call's reply");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus signal before the reply is skipped");
}

/* the real dbus-daemon Hello reply carries DESTINATION and SENDER
 * header fields and flags 0x01 - the client must parse it */
static void test_daemon_reply_shape(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "daemon reply shape");
	s.expect_ncalls = 2;
	s.expect_hex[0] = GOLDEN_CALL_EMPTY;
	s.reply_hex[0] = GOLDEN_REPLY_EMPTY;
	s.expect_hex[1] = GOLDEN_CALL_S2;
	s.reply_hex[1] = GOLDEN_REPLY_DAEMON;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_arg args[1] = { { 's', .s = "AA:BB:CC:DD:EE:FF" } };
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, &out, err, sizeof err), 0,
				     "empty reply accepted");
			CHECK(out != NULL && out->type == DBUS_VALUE_EMPTY,
			      "empty body parses as DBUS_VALUE_EMPTY");
			dbus_value_free(out);
			out = NULL;
			CHECK_INT_EQ(dbus_call(&c, "GetStatus", "s", args, NULL,
					       NULL, &out, err, sizeof err), 0,
				     "daemon-shaped reply accepted");
			CHECK(out != NULL && out->type == DBUS_VALUE_STRING &&
			      out->str != NULL && strcmp(out->str, ":1.0") == 0,
			      "the body of the daemon-shaped reply is \":1.0\"");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus daemon-shaped reply (DEST+SENDER)");
}

static void test_bad_replies(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	/* unexpected message type (127 is not CALL/RETURN/ERROR/SIGNAL) */
	scenario_init(&s, "bad type");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_BAD_TYPE;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);
	{
		struct dbus_client c;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, NULL, err, sizeof err),
				     -1, "a garbage message type is rejected");
			CHECK(strstr(err, "unexpected reply type 127") != NULL,
			      "the error names the message type");
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for a garbage message type");

	/* bad endian marker */
	scenario_init(&s, "bad endian");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_BAD_ENDIAN;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);
	{
		struct dbus_client c;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, NULL, err, sizeof err),
				     -1, "a wrong endian byte is rejected");
			CHECK(strstr(err, "endian") != NULL,
			      "the error mentions the endian byte");
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for a bad endian byte");

	/* oversized reply */
	scenario_init(&s, "oversized");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_OVERSIZED;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);
	{
		struct dbus_client c;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, NULL, err, sizeof err),
				     -1, "an oversized reply is rejected");
			CHECK(strstr(err, "too large") != NULL,
			      "the error mentions the size");
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip for an oversized reply");
}

static void test_chunked_reply(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "chunked reply");
	s.expect_ncalls = 1;
	s.reply_hex[0] = GOLDEN_REPLY_S;
	s.reply_chunks = 2;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;
		struct dbus_value *out = NULL;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Reload", "", NULL, NULL,
					       NULL, &out, err, sizeof err),
				     0, "a reply split into two writes parses");
			CHECK(out && out->type == DBUS_VALUE_STRING &&
			      !strcmp(out->str, "status-line"),
			      "chunked reply content is intact");
			dbus_value_free(out);
			dbus_disconnect(&c);
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus round-trip with a chunked reply");
}

static void test_auth_rejected(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "auth rejected");
	s.auth_reject = 1;
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;

		CHECK_INT_EQ(dbus_connect(&c, addr, err, sizeof err), -1,
			     "REJECTED fails the connect");
		CHECK(strstr(err, "rejected") != NULL,
		      "the error reports the rejection");
		dbus_disconnect(&c);
	}
	finish_server(&s, th, "fake bus saw a correct AUTH line then rejected");
}

static void test_address_parameters(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "address parameters");
	s.expect_ncalls = 0;
	th = start_server(&s, sock, sizeof sock);
	/* dbus-daemon --print-address appends ",guid=..." after the path;
	 * the client must stop the value at the ',' */
	snprintf(addr, sizeof addr,
		 "unix:path=%s,guid=0123456789abcdef0123456789abcdef", sock);

	{
		struct dbus_client c;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK(1, "an address with extra parameters connects");
			dbus_disconnect(&c);
		} else {
			CHECK(0, "an address with extra parameters connects");
		}
	}
	finish_server(&s, th, "fake bus round-trip for a parameterized address");
}

static void test_connect_refused(void)
{
	struct dbus_client c;
	char err[256];

	CHECK_INT_EQ(dbus_connect(&c,
				  "unix:path=/tmp/lgmagic-no-such-bus.sock",
				  err, sizeof err), -1,
		     "connecting to a missing socket fails");
	CHECK(strstr(err, "cannot connect") != NULL,
	      "the error is a connection error");
	dbus_disconnect(&c);
}

static void test_validation(void)
{
	struct scenario s;
	pthread_t th;
	char sock[512], addr[560], err[256];

	scenario_init(&s, "validation");
	s.expect_ncalls = 0;		/* the invalid call is never sent */
	th = start_server(&s, sock, sizeof sock);
	snprintf(addr, sizeof addr, "unix:path=%s", sock);

	{
		struct dbus_client c;

		if (dbus_connect(&c, addr, err, sizeof err) == 0) {
			CHECK_INT_EQ(dbus_call(&c, "Foo", "x", NULL, NULL,
					       NULL, NULL, err, sizeof err),
				     -1, "an unsupported input signature fails");
			CHECK(strstr(err, "unsupported input signature") != NULL,
			      "the error names the signature");
			dbus_disconnect(&c);

			CHECK_INT_EQ(dbus_call(&c, "Foo", "", NULL, NULL,
					       NULL, NULL, err, sizeof err),
				     -1, "calling after disconnect fails");
			CHECK(strstr(err, "not connected") != NULL,
			      "the error says the client is not connected");
		} else {
			CHECK(0, "connect to the fake bus");
		}
	}
	finish_server(&s, th, "fake bus saw handshake only (bad call unsent)");

	dbus_value_free(NULL);		/* must be a no-op */
	CHECK(1, "dbus_value_free(NULL) is a safe no-op");
}

int main(void)
{
	TEST_BEGIN();
	test_golden_sd();
	test_golden_s_reply();
	test_golden_empty();
	test_two_calls_serials();
	test_reply_as();
	test_reply_vs();
	test_reply_error();
	test_wrong_serial();
	test_signal_skip();
	test_daemon_reply_shape();
	test_bad_replies();
	test_chunked_reply();
	test_auth_rejected();
	test_address_parameters();
	test_connect_refused();
	test_validation();
	TEST_SUMMARY("test_dbus_client");
	return tu_fail_count ? 1 : 0;
}

