/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * test_madgwick.c - golden-trace replay for the Madgwick AHRS filter.
 *
 * Fixture: ../testdata/madgwick_ref.csv (relative to the tools/ dir; tests
 * run with cwd = tools/), header
 *
 *     gx,gy,gz,ax,ay,az,qw,qx,qy,qz
 *
 * with gyro in rad/s and accel in m/s^2 (already calibration-corrected and
 * R_aligned - exactly what scripts/display_imu.py feeds to Madgwick).  The
 * qw,qx,qy,qz columns are the quaternion AFTER the update of that row.
 *
 * Replay protocol (mirrors display_imu.py):
 *   madgwick_init(beta = 0.1, sample_freq = 50.0,
 *                 q0 = accel_to_quat(accel of row 0));
 *   for each row i:
 *       madgwick_update_imu(row i gyro, row i accel);
 *       compare the resulting quaternion with row i's q within 1e-6.
 *
 * The comparison is sign-tolerant: q and -q are the same orientation, so a
 * component passes when min(|a-b|, |a+b|) <= tol for every component.
 *
 * The fixture is generated by the reference implementation (Python `ahrs`,
 * float64) and must be committed; a missing fixture is a test FAILURE.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "test_util.h"
#include "madgwick.h"
#include "csv.h"		/* only for struct imu_sample layout reuse */
#include "matrix.h"

struct ref_row {
	double gx, gy, gz;	/* gyro, rad/s */
	double ax, ay, az;	/* accel, m/s^2 */
	double qw, qx, qy, qz;	/* reference quaternion after the update */
};

/* Parse the fixture into a malloc'd array of rows.
 * Returns the row count, or -1 on any format error. */
static long load_ref(const char *path, struct ref_row **out)
{
	FILE *f;
	char line[1024];
	struct ref_row *rows = NULL;
	size_t cap = 0, n = 0;
	long lineno = 0;

	f = fopen(path, "r");
	if (!f)
		return -1;
	while (fgets(line, sizeof(line), f)) {
		double v[10];
		int i;
		char *p = line, *end;
		lineno++;
		/* skip blank lines */
		if (line[0] == '\n' || line[0] == '\r' || line[0] == '\0')
			continue;
		if (lineno == 1) {
			/* header line; check it starts with the gyro axis */
			if (strncmp(line, "gx,gy,gz,ax,ay,az,qw,qx,qy,qz",
				    strlen("gx,gy,gz,ax,ay,az,qw,qx,qy,qz"))
			    != 0) {
				fprintf(stderr,
					"test_madgwick: bad header in %s: %s",
					path, line);
				free(rows);
				fclose(f);
				return -1;
			}
			continue;
		}
		for (i = 0; i < 10; i++) {
			v[i] = strtod(p, &end);
			if (end == p) {
				/* field must be a number */
				fprintf(stderr,
					"test_madgwick: garbage at %s:%ld "
					"field %d\n", path, lineno, i);
				free(rows);
				fclose(f);
				return -1;
			}
			p = end;
			if (i < 9) {
				if (*p == ',')
					p++;
				else {
					fprintf(stderr,
						"test_madgwick: missing "
						"comma at %s:%ld field %d\n",
						path, lineno, i);
					free(rows);
					fclose(f);
					return -1;
				}
			}
		}
		if (n == cap) {
			cap = cap ? cap * 2 : 64;
			rows = realloc(rows, cap * sizeof(*rows));
			if (!rows) {
				fclose(f);
				return -1;
			}
		}
		rows[n].gx = v[0]; rows[n].gy = v[1]; rows[n].gz = v[2];
		rows[n].ax = v[3]; rows[n].ay = v[4]; rows[n].az = v[5];
		rows[n].qw = v[6]; rows[n].qx = v[7];
		rows[n].qy = v[8]; rows[n].qz = v[9];
		n++;
	}
	fclose(f);
	*out = rows;
	return (long)n;
}

int main(void)
{
	char path[4096];
	struct ref_row *rows = NULL;
	long n;
	struct madgwick_state st;
	vec3 a0;
	quat q0;
	int fails = 0;
	long i;
	const double TOL = 1e-6;

	TEST_BEGIN();
	if (tu_fixture_path(path, sizeof(path), "madgwick_ref.csv") != 0) {
		CHECK(0, "fixture ../testdata/madgwick_ref.csv exists "
		      "(fixtures must be committed)");
		TEST_SUMMARY("test_madgwick");
		return 1;
	}
	n = load_ref(path, &rows);
	CHECK(n > 0, "fixture madgwick_ref.csv parses to at least one row");
	if (n <= 0) {
		if (rows)
			free(rows);
		TEST_SUMMARY("test_madgwick");
		return 1;
	}
	printf("  (replaying %ld rows from %s)\n", n, path);

	/* q0 = accel_to_quat(accel of row 0), like display_imu.py */
	a0.x = rows[0].ax;
	a0.y = rows[0].ay;
	a0.z = rows[0].az;
	q0 = accel_to_quat(a0);
	madgwick_init(&st, 0.1, 50.0, q0);

	for (i = 0; i < n; i++) {
		double w, x, y, z;
		madgwick_update_imu(&st,
				    rows[i].gx, rows[i].gy,
				    rows[i].gz, rows[i].ax,
				    rows[i].ay, rows[i].az);
		w = st.q.w; x = st.q.x; y = st.q.y; z = st.q.z;
		/* sign-consistent comparison: q and -q are the same */
		if (fmin(fabs(w - rows[i].qw), fabs(w + rows[i].qw)) > TOL ||
		    fmin(fabs(x - rows[i].qx), fabs(x + rows[i].qx)) > TOL ||
		    fmin(fabs(y - rows[i].qy), fabs(y + rows[i].qy)) > TOL ||
		    fmin(fabs(z - rows[i].qz), fabs(z + rows[i].qz)) > TOL) {
			fails++;
			if (fails <= 5) {
				printf("  mismatch at row %ld: got (%.9f %.9f "
				       "%.9f %.9f), ref (%.9f %.9f %.9f "
				       "%.9f)\n", i, w, x, y, z, rows[i].qw,
				       rows[i].qx, rows[i].qy, rows[i].qz);
			}
		}
	}
	if (fails)
		printf("  (%d of %ld rows mismatched)\n", fails, n);
	CHECK(fails == 0,
	      "madgwick_update_imu matches the reference trace within 1e-6 "
	      "(sign-tolerant)");
	free(rows);
	TEST_SUMMARY("test_madgwick");
	return tu_fail_count ? 1 : 0;
}
