#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# sync-version.sh - stamp the version into every file that carries it.
#
# The single source of truth is the GitHub repository variable VERSION
# (imported into CI as ${{ vars.VERSION }}).  The stamps below are
# token-only and date-free on purpose: the CI drift-gate job re-runs
# this script with $VERSION and requires a clean git diff, so the
# script must be idempotent.  Changelog *entries* are hand-written;
# this script only rewrites the version tokens.
#
# Usage:
#   sync-version.sh [VERSION]   stamp VERSION everywhere (v-prefix ok;
#                               default: read from dkms.conf)
#   sync-version.sh --check     verify all stamp sites agree and are
#                               semver-shaped; no writes, exit 1 on drift

set -euo pipefail

cd "$(dirname -- "$0")/.."  # repo root

VERSION_RE='^[0-9]+\.[0-9]+\.[0-9]+$'

die() { echo "sync-version.sh: $*" >&2; exit 1; }

# Portable in-place stamp (BSD sed has no -i).
stamp() {
	sed -e "$1" "$2" > "$2.tmp" && mv "$2.tmp" "$2"
}

# read_site FILE SITE -> the version found at that site ("" if none).
read_site() {
	case "$2" in
	dkms)      sed -n 's/^PACKAGE_VERSION="\([^"]*\)".*/\1/p' "$1" | head -n1 ;;
	buildver)  sed -n 's/^#define LGMAGIC_VERSION "\([^"]*\)".*/\1/p' "$1" | head -n1 ;;
	apiver)    sed -n 's/^#define LG_API_VERSION "\([^"]*\)".*/\1/p' "$1" | head -n1 ;;
	pkgbuild)  sed -n 's/^pkgver=\(.*\)/\1/p' "$1" | head -n1 ;;
	spec)      sed -n 's/^Version:[[:space:]]*\(.*\)/\1/p' "$1" | head -n1 ;;
	changelog) sed -n '1s/^lgmagic (\([^)]*\)).*/\1/p' "$1" | sed 's/-[0-9][0-9]*$//' | head -n1 ;;
	*) die "unknown site $2" ;;
	esac
}

# ----------------------------------------------------------------------
# --check: every site must yield the same semver; no writes.
if [ "$#" -ge 1 ] && [ "$1" = "--check" ]; then
	if [ "$#" -ne 1 ]; then
		die "--check takes no other arguments"
	fi
	[ -f dkms.conf ] || die "missing dkms.conf"
	[ -f tools/include/build_version.h ] || die "missing tools/include/build_version.h"
	[ -f debian/changelog ] || die "missing debian/changelog"
	[ -f rpm/lgmagic.spec ] || die "missing rpm/lgmagic.spec"
	[ -f arch/PKGBUILD ] || die "missing arch/PKGBUILD"

	v_dkms=$(read_site dkms.conf dkms)
	v_build=$(read_site tools/include/build_version.h buildver)
	v_deb=$(read_site debian/changelog changelog)
	v_spec=$(read_site rpm/lgmagic.spec spec)
	v_arch=$(read_site arch/PKGBUILD pkgbuild)
	v_api=$(read_site tools/include/daemon_bus.h apiver)

	bad=""
	for v in "$v_dkms" "$v_build" "$v_deb" "$v_spec" "$v_arch"; do
		if ! printf '%s\n' "$v" | grep -qE "$VERSION_RE"; then
			bad=1
		fi
	done
	if [ -z "$bad" ] \
	   && [ "$v_dkms" = "$v_build" ] \
	   && [ "$v_build" = "$v_deb" ] \
	   && [ "$v_deb" = "$v_spec" ] \
	   && [ "$v_spec" = "$v_arch" ] \
	   && [ "$v_api" = "${v_dkms%.*}" ]; then
		echo "version sync OK: $v_dkms"
		exit 0
	fi
	echo "sync-version.sh: version drift detected:" >&2
	printf '  dkms.conf:                      %s\n' "$v_dkms" >&2
	printf '  tools/include/build_version.h:  %s\n' "$v_build" >&2
	printf '  debian/changelog (top entry):   %s\n' "$v_deb" >&2
	printf '  rpm/lgmagic.spec (Version):     %s\n' "$v_spec" >&2
	printf '  arch/PKGBUILD (pkgver):         %s\n' "$v_arch" >&2
	printf '  LG_API_VERSION (want %s):       %s\n' "${v_dkms%.*}" "$v_api" >&2
	exit 1
fi

# ----------------------------------------------------------------------
# Stamp mode.  An explicit empty argument (CI: empty vars.VERSION) is an
# error - never fall back silently, the drift-gate must fail loudly.
version=""
if [ "$#" -gt 1 ]; then
	die "too many arguments (usage: sync-version.sh [VERSION] | sync-version.sh --check)"
fi
if [ "$#" -ge 1 ]; then
	version="${1#v}"
	if [ -z "$version" ]; then
		die "empty VERSION argument (check the VERSION repository variable: gh variable get VERSION --repo sirfragles/lgmagic)"
	fi
else
	[ -f dkms.conf ] || die "no version given and no dkms.conf to read it from"
	version=$(read_site dkms.conf dkms)
	[ -n "$version" ] || die "could not read PACKAGE_VERSION from dkms.conf"
fi

if ! printf '%s\n' "$version" | grep -qE "$VERSION_RE"; then
	die "invalid version '$version' (want MAJOR.MINOR.PATCH, e.g. 0.0.1)"
fi
major_minor=$(printf '%s\n' "$version" | cut -d. -f1-2)

stamp 's/^PACKAGE_VERSION="[^"]*"/PACKAGE_VERSION="'"$version"'"/' dkms.conf

if [ ! -f tools/include/build_version.h ]; then
	cat > tools/include/build_version.h <<'EOF'
/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Build-time version stamp.  Generated by scripts/sync-version.sh; the
 * single source of truth is the GitHub repository variable VERSION.
 * Do not edit by hand.
 */
#ifndef LGMAGIC_BUILD_VERSION_H
#define LGMAGIC_BUILD_VERSION_H

#define LGMAGIC_VERSION "0.0.1"

#endif /* LGMAGIC_BUILD_VERSION_H */
EOF
fi
stamp 's/^#define LGMAGIC_VERSION "[^"]*"/#define LGMAGIC_VERSION "'"$version"'"/' tools/include/build_version.h
stamp 's/^#define LG_API_VERSION "[^"]*"/#define LG_API_VERSION "'"$major_minor"'"/' tools/include/daemon_bus.h
stamp 's/^pkgver=.*/pkgver='"$version"'/' arch/PKGBUILD
stamp 's/^Version:.*/Version:        '"$version"'/' rpm/lgmagic.spec
# NOTE: the pattern must NOT end with ')' after '[0-9.]*' - BSD sed
# (macOS) fails to match '([0-9.]*)' and '([0-9][0-9.]*)' in BRE.  The
# version token ends at the '-', so no closing paren is needed.
stamp '1s/^lgmagic ([0-9.]*/lgmagic ('"$version"'/' debian/changelog

echo "synced to $version (LG_API_VERSION $major_minor)"
